name: Publish Rust Docs

on:
  push:
    tags:
      - v*

jobs:
  deploy-docs:
    name: Deploy docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
            target: wasm32-unknown-unknown

      # With rustup's nice new toml format, we just need to run rustup show to install the toolchain
      # https://github.com/actions-rs/toolchain/issues/126#issuecomment-782989659
      - name: Setup Rust toolchain
        run: rustup show

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-doc-${{ hashFiles('**/Cargo.lock') }}

      - name: Build rustdocs
        uses: actions-rs/cargo@v1
        env:
          CARGO_INCREMENTAL: "0"
        with:
          command: doc
          args: --all --no-deps

      # Make an index.html file so we start at the moonbeam_runtime page
      # Copied from https://github.com/substrate-developer-hub/rustdocs/blob/master/index.html
      - name: Make index.html
        run: echo "<meta http-equiv=refresh content=0;url=fs_node_runtime/index.html>" > ./target/doc/index.html

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./target/doc
